
exports.tier1Nations = ["Algeria","Cameroon","Cote D'Ivoire","DR Congo","Guadeloupe","Guinea","Martinique","Mali","Morocco","Senegal"];
exports.tier2Nations =  ["Angola", "Benin", "Burkina Faso", "Central African Republic", "Comoros","Congo", "French Guiana", "Gabon", "Guinea-Bissau", "Togo", "Tunisia"];
exports.tier3Nations = ["Argentina", "Cape Verde", "Chad", "Ghana", "Haiti","Italy", "Madagascar", "Mauritania", "Nigeria", "Portugal", "Reunion", "Spain"];


exports.countryFlags = {
    "Algeria": ":flag_dz:",
    "Cameroon": ":flag_cm:",
    "Cote D'Ivoire": ":flag_ci:",
    "DR Congo": ":flag_cd:",
    "Guadeloupe": ":flag_gp:",
    "Guinea": ":flag_gn:",
    "Martinique": ":flag_mq:",
    "Mali": ":flag_ml:",
    "Morocco": ":flag_ma:",
    "Senegal": ":flag_sn:",
    "Angola": ":flag_ao:",
    "Benin": ":flag_bj:",
    "Burkina Faso": ":flag_bf:",
    "Central African Republic": ":flag_cf:",
    "Comoros": ":flag_km:",
    "Congo": ":flag_cg:",
    "French Guiana": ":flag_gf:",
    "Gabon": ":flag_ga:",
    "Guinea-Bissau": ":flag_gw:",
    "Togo": ":flag_tg:",
    "Tunisia": ":flag_tn:",
    "Argentina": ":flag_ar:",
    "Cape Verde": ":flag_cv:",
    "Chad": ":flag_td:",
    "Ghana": ":flag_gh:",
    "Haiti": ":flag_ht:",
    "Italy": ":flag_it:",
    "Madagascar": ":flag_mg:",
    "Mauritania": ":flag_mr:",
    "Nigeria": ":flag_ng:",
    "Portugal": ":flag_pt:",
    "Reunion": ":flag_re:",
    "Spain": ":flag_es:"
};


exports.countryCodes = {
    "Afrikaans": "afk",
    "African": "afr",
    "Akan": "aka",
    "Albanian": "alb",
    "Algonquin": "alg",
    "Indigenous American": "ame",
    "New World Mythology": "amem",
    "Amharic": "amh",
    "Ancient": "anci",
    "Apache": "apa",
    "Arabic": "ara",
    "Armenian": "arm",
    "Assamese": "asm",
    "Asturian": "ast",
    "Astronomy": "astr",
    "Indigenous Australian": "aus",
    "Avar": "ava",
    "Aymara": "aym",
    "Azerbaijani": "aze",
    "Balinese": "bal",
    "Basque": "bas",
    "Belarusian": "bel",
    "Bengali": "ben",
    "Berber": "ber",
    "Bhutanese": "bhu",
    "Biblical (All)": "bibl",
    "Bosnian": "bos",
    "Breton": "bre",
    "Bashkir": "bsh",
    "Bulgarian": "bul",
    "Burmese": "bur",
    "Catalan": "cat",
    "Ancient Celtic": "cela",
    "Celtic Mythology": "celm",
    "Chewa": "cew",
    "Chamorro": "cha",
    "Chechen": "che",
    "Chinese": "chi",
    "Cherokee": "chk",
    "Choctaw": "cht",
    "Cheyenne": "chy",
    "Circassian": "cir",
    "Comorian": "cmr",
    "Comanche": "com",
    "Coptic": "cop",
    "Cornish": "cor",
    "Cree": "cre",
    "Croatian": "cro",
    "Corsican": "crs",
    "Czech": "cze",
    "Danish": "dan",
    "Dagestani": "dgs",
    "Dhivehi": "dhi",
    "Dargin": "drg",
    "Dutch": "dut",
    "Ancient Egyptian": "egya",
    "Egyptian Mythology": "egym",
    "Xmas Elf": "elf",
    "English": "eng",
    "Anglo-Saxon": "enga",
    "Esperanto": "esp",
    "Estonian": "est",
    "Ethiopian": "eth",
    "Ewe": "ewe",
    "Faroese": "fae",
    "Fairy": "fairy",
    "Fijian": "fij",
    "Filipino": "fil",
    "Finnish": "fin",
    "Flemish": "fle",
    "Gluttakh": "fntsg",
    "Monstrall": "fntsm",
    "Orinami": "fntso",
    "Romanto": "fntsr",
    "Simitiq": "fntss",
    "Tsang": "fntst",
    "Xalaxxi": "fntsx",
    "French": "fre",
    "Frisian": "fri",
    "Fula": "ful",
    "Ga": "gaa",
    "Galician": "gal",
    "Ganda": "gan",
    "Georgian": "geo",
    "German": "ger",
    "Ancient Germanic": "gmca",
    "Goth": "goth",
    "Greek": "gre",
    "Ancient Greek": "grea",
    "Greek Mythology": "grem",
    "Greenlandic": "grn",
    "Guarani": "gua",
    "Gujarati": "guj",
    "Hausa": "hau",
    "Hawaiian": "haw",
    "Hillbilly": "hb",
    "Hebrew": "heb",
    "Hindi": "hin",
    "Hippy": "hippy",
    "History": "hist",
    "Hmong": "hmo",
    "Hungarian": "hun",
    "Ibibio": "ibi",
    "Icelandic": "ice",
    "Igbo": "igb",
    "Indian": "ind",
    "Hindu Mythology": "indm",
    "Ingush": "ing",
    "Indonesian": "ins",
    "Inuit": "inu",
    "Irish": "iri",
    "Iroquois": "iro",
    "Italian": "ita",
    "Japanese": "jap",
    "Javanese": "jav",
    "Jèrriais": "jer",
    "Jewish": "jew",
    "Kannada": "kan",
    "Kazakh": "kaz",
    "Khmer": "khm",
    "Kiga": "kig",
    "Kikuyu": "kik",
    "Kreatyve": "kk",
    "Kongo": "kon",
    "Korean": "kor",
    "Kurdish": "kur",
    "Kyrgyz": "kyr",
    "Lao": "lao",
    "Latvian": "lat",
    "Limburgish": "lim",
    "Literature": "lite",
    "Arthurian Romance": "litk",
    "Lithuanian": "lth",
    "Luhya": "luh",
    "Luo": "luo",
    "Macedonian": "mac",
    "Maguindanao": "mag",
    "Maltese": "mal",
    "Manx": "man",
    "Maori": "mao",
    "Mapuche": "map",
    "Mayan": "may",
    "Mbundu": "mbu",
    "Medieval": "medi",
    "Malayalam": "mlm",
    "Malay": "mly",
    "Mohawk": "moh",
    "Mongolian": "mon",
    "Mormon": "morm",
    "Marathi": "mrt",
    "Mwera": "mwe",
    "Mythology": "myth",
    "Nahuatl": "nah",
    "Navajo": "nav",
    "Ndebele": "nde",
    "Ancient Near Eastern": "neaa",
    "Near Eastern Mythology": "neam",
    "Nepali": "nep",
    "Norwegian": "nor",
    "Norman": "nrm",
    "Nuu-chah-nulth": "nuu",
    "Occitan": "occ",
    "Odia": "odi",
    "Ojibwe": "oji",
    "Oneida": "one",
    "Oromo": "oro",
    "Ossetian": "oss",
    "Pashto": "pas",
    "Picard": "pcd",
    "Persian": "per",
    "Pet": "pets",
    "Pintupi": "pin",
    "Polish": "pol",
    "Popular Culture": "popu",
    "Portuguese": "por",
    "Powhatan": "pow",
    "Punjabi": "pun",
    "Quechua": "que",
    "Rapa Nui": "rap",
    "Romanian": "rmn",
    "Ancient Roman": "roma",
    "Roman Mythology": "romm",
    "Russian": "rus",
    "Sami": "sam",
    "Sardinian": "sar",
    "Low German": "sax",
    "Ancient Scandinavian": "scaa",
    "Norse Mythology": "scam",
    "Scottish": "sco",
    "Scots": "sct",
    "Seneca": "sen",
    "Serbian": "ser",
    "Shawnee": "sha",
    "Shona": "sho",
    "Sicilian": "sic",
    "Siksika": "sik",
    "Sinhalese": "sin",
    "Sioux": "sio",
    "Slavic": "sla",
    "-": "slaa",
    "Slavic Mythology": "slam",
    "Slovak": "slk",
    "Slovene": "sln",
    "Samoan": "smn",
    "Somali": "som",
    "Sorbian": "sor",
    "Sotho": "sot",
    "Spanish": "spa",
    "Sundanese": "sun",
    "Swahili": "swa",
    "Swedish": "swe",
    "Swazi": "swz",
    "Tagalog": "tag",
    "Tahitian": "tah",
    "Tajik": "taj",
    "Tamil": "tam",
    "Tatar": "tat",
    "Tausug": "tau",
    "Telugu": "tel",
    "Thai": "tha",
    "Theology": "theo",
    "Tibetan": "tib",
    "Turkmen": "tkm",
    "Tongan": "ton",
    "Tooro": "too",
    "Transformer": "trans",
    "Tswana": "tsw",
    "Tuareg": "tua",
    "Tumbuka": "tum",
    "Tupi": "tup",
    "Turkish": "tur",
    "Ukrainian": "ukr",
    "Urdu": "urd",
    "Urhobo": "urh",
    "American": "usa",
    "Uyghur": "uyg",
    "Uzbek": "uzb",
    "Various": "vari",
    "Vietnamese": "vie",
    "Welsh": "wel",
    "Witch": "witch",
    "Walloon": "wln",
    "Wrestler": "wrest",
    "Xhosa": "xho",
    "Yao": "yao",
    "Yolngu": "yol",
    "Yoruba": "yor",
    "Zapotec": "zap",
    "Zulu": "zul"
}  