
exports.tier1Nations = ["DR Congo","Morocco","Senegal"];
exports.tier2Nations =  ["Ghana", "Cote D'Ivoire", "Guinea", "Netherlands", "Italy","France","Spain","Turkey","Serbia"];
exports.tier3Nations = ["Angola","Algeria", "Cameroon", "Portugal", "Brazil", "Germany", "Syria", "Nigeria", "Greece", "Romania","Poland"];

exports.playstyles = ["Chip Shot", "Finesse Shot", "Power Header", "Power Shot", "Dead Ball", "Incisive Pass", "Pinged Pass", "Long Ball Pass", "Tiki Taka", "Whipped Pass", "First Touch", "Flair", "Press Proven", "Rapid", "Technical", "Trickster", "Block", "Bruiser", "Intercept", "Jockey", "Slide Tackle", "Anticipate", "Acrobatic", "Aerial", "Trivela", "Relentless", "Quick Step", "Long Throw", "Far Throw", "Footwork", "Cross Claimer", "Rush Out", "Far Reach", "Quick Reflexes"];

exports.countryFlags = {
    "Algeria": ":flag_dz:",
    "Cameroon": ":flag_cm:",
    "Cote D'Ivoire": ":flag_ci:",
    "DR Congo": ":flag_cd:",
    "Guinea": ":flag_gn:",
    "Morocco": ":flag_ma:",
    "Senegal": ":flag_sn:",
    "Angola": ":flag_ao:",
    "Ghana": ":flag_gh:",
    "Italy": ":flag_it:",
    "Nigeria": ":flag_ng:",
    "Portugal": ":flag_pt:",
    "Spain": ":flag_es:",
    "Netherlands": ":flag_nl:",
    "France": ":flag_fr:",
    "Turkey": ":flag_tr:",
    "Serbia": ":flag_rs:",
    "Germany": ":flag_de:",
    "Brazil": ":flag_br:",
    "Greece": ":flag_gr:",
    "Romania": ":flag_ro:",
    "Poland": ":flag_pl:"
};


exports.countryCodes = {
    "Afrikaans": "afk",
    "African": "afr",
    "Akan": "aka",
    "Albanian": "alb",
    "Algonquin": "alg",
    "Indigenous American": "ame",
    "New World Mythology": "amem",
    "Amharic": "amh",
    "Ancient": "anci",
    "Apache": "apa",
    "Arabic": "ara",
    "Armenian": "arm",
    "Assamese": "asm",
    "Asturian": "ast",
    "Astronomy": "astr",
    "Indigenous Australian": "aus",
    "Avar": "ava",
    "Aymara": "aym",
    "Azerbaijani": "aze",
    "Balinese": "bal",
    "Basque": "bas",
    "Belarusian": "bel",
    "Bengali": "ben",
    "Berber": "ber",
    "Bhutanese": "bhu",
    "Biblical (All)": "bibl",
    "Bosnian": "bos",
    "Breton": "bre",
    "Bashkir": "bsh",
    "Bulgarian": "bul",
    "Burmese": "bur",
    "Catalan": "cat",
    "Ancient Celtic": "cela",
    "Celtic Mythology": "celm",
    "Chewa": "cew",
    "Chamorro": "cha",
    "Chechen": "che",
    "Chinese": "chi",
    "Cherokee": "chk",
    "Choctaw": "cht",
    "Cheyenne": "chy",
    "Circassian": "cir",
    "Comorian": "cmr",
    "Comanche": "com",
    "Coptic": "cop",
    "Cornish": "cor",
    "Cree": "cre",
    "Croatian": "cro",
    "Corsican": "crs",
    "Czech": "cze",
    "Danish": "dan",
    "Dagestani": "dgs",
    "Dhivehi": "dhi",
    "Dargin": "drg",
    "Dutch": "dut",
    "Ancient Egyptian": "egya",
    "Egyptian Mythology": "egym",
    "Xmas Elf": "elf",
    "English": "eng",
    "Anglo-Saxon": "enga",
    "Esperanto": "esp",
    "Estonian": "est",
    "Ethiopian": "eth",
    "Ewe": "ewe",
    "Faroese": "fae",
    "Fairy": "fairy",
    "Fijian": "fij",
    "Filipino": "fil",
    "Finnish": "fin",
    "Flemish": "fle",
    "Gluttakh": "fntsg",
    "Monstrall": "fntsm",
    "Orinami": "fntso",
    "Romanto": "fntsr",
    "Simitiq": "fntss",
    "Tsang": "fntst",
    "Xalaxxi": "fntsx",
    "French": "fre",
    "Frisian": "fri",
    "Fula": "ful",
    "Ga": "gaa",
    "Galician": "gal",
    "Ganda": "gan",
    "Georgian": "geo",
    "German": "ger",
    "Ancient Germanic": "gmca",
    "Goth": "goth",
    "Greek": "gre",
    "Ancient Greek": "grea",
    "Greek Mythology": "grem",
    "Greenlandic": "grn",
    "Guarani": "gua",
    "Gujarati": "guj",
    "Hausa": "hau",
    "Hawaiian": "haw",
    "Hillbilly": "hb",
    "Hebrew": "heb",
    "Hindi": "hin",
    "Hippy": "hippy",
    "History": "hist",
    "Hmong": "hmo",
    "Hungarian": "hun",
    "Ibibio": "ibi",
    "Icelandic": "ice",
    "Igbo": "igb",
    "Indian": "ind",
    "Hindu Mythology": "indm",
    "Ingush": "ing",
    "Indonesian": "ins",
    "Inuit": "inu",
    "Irish": "iri",
    "Iroquois": "iro",
    "Italian": "ita",
    "Japanese": "jap",
    "Javanese": "jav",
    "Jèrriais": "jer",
    "Jewish": "jew",
    "Kannada": "kan",
    "Kazakh": "kaz",
    "Khmer": "khm",
    "Kiga": "kig",
    "Kikuyu": "kik",
    "Kreatyve": "kk",
    "Kongo": "kon",
    "Korean": "kor",
    "Kurdish": "kur",
    "Kyrgyz": "kyr",
    "Lao": "lao",
    "Latvian": "lat",
    "Limburgish": "lim",
    "Literature": "lite",
    "Arthurian Romance": "litk",
    "Lithuanian": "lth",
    "Luhya": "luh",
    "Luo": "luo",
    "Macedonian": "mac",
    "Maguindanao": "mag",
    "Maltese": "mal",
    "Manx": "man",
    "Maori": "mao",
    "Mapuche": "map",
    "Mayan": "may",
    "Mbundu": "mbu",
    "Medieval": "medi",
    "Malayalam": "mlm",
    "Malay": "mly",
    "Mohawk": "moh",
    "Mongolian": "mon",
    "Mormon": "morm",
    "Marathi": "mrt",
    "Mwera": "mwe",
    "Mythology": "myth",
    "Nahuatl": "nah",
    "Navajo": "nav",
    "Ndebele": "nde",
    "Ancient Near Eastern": "neaa",
    "Near Eastern Mythology": "neam",
    "Nepali": "nep",
    "Norwegian": "nor",
    "Norman": "nrm",
    "Nuu-chah-nulth": "nuu",
    "Occitan": "occ",
    "Odia": "odi",
    "Ojibwe": "oji",
    "Oneida": "one",
    "Oromo": "oro",
    "Ossetian": "oss",
    "Pashto": "pas",
    "Picard": "pcd",
    "Persian": "per",
    "Pet": "pets",
    "Pintupi": "pin",
    "Polish": "pol",
    "Popular Culture": "popu",
    "Portuguese": "por",
    "Powhatan": "pow",
    "Punjabi": "pun",
    "Quechua": "que",
    "Rapa Nui": "rap",
    "Romanian": "rmn",
    "Ancient Roman": "roma",
    "Roman Mythology": "romm",
    "Russian": "rus",
    "Sami": "sam",
    "Sardinian": "sar",
    "Low German": "sax",
    "Ancient Scandinavian": "scaa",
    "Norse Mythology": "scam",
    "Scottish": "sco",
    "Scots": "sct",
    "Seneca": "sen",
    "Serbian": "ser",
    "Shawnee": "sha",
    "Shona": "sho",
    "Sicilian": "sic",
    "Siksika": "sik",
    "Sinhalese": "sin",
    "Sioux": "sio",
    "Slavic": "sla",
    "-": "slaa",
    "Slavic Mythology": "slam",
    "Slovak": "slk",
    "Slovene": "sln",
    "Samoan": "smn",
    "Somali": "som",
    "Sorbian": "sor",
    "Sotho": "sot",
    "Spanish": "spa",
    "Sundanese": "sun",
    "Swahili": "swa",
    "Swedish": "swe",
    "Swazi": "swz",
    "Tagalog": "tag",
    "Tahitian": "tah",
    "Tajik": "taj",
    "Tamil": "tam",
    "Tatar": "tat",
    "Tausug": "tau",
    "Telugu": "tel",
    "Thai": "tha",
    "Theology": "theo",
    "Tibetan": "tib",
    "Turkmen": "tkm",
    "Tongan": "ton",
    "Tooro": "too",
    "Transformer": "trans",
    "Tswana": "tsw",
    "Tuareg": "tua",
    "Tumbuka": "tum",
    "Tupi": "tup",
    "Turkish": "tur",
    "Ukrainian": "ukr",
    "Urdu": "urd",
    "Urhobo": "urh",
    "American": "usa",
    "Uyghur": "uyg",
    "Uzbek": "uzb",
    "Various": "vari",
    "Vietnamese": "vie",
    "Welsh": "wel",
    "Witch": "witch",
    "Walloon": "wln",
    "Wrestler": "wrest",
    "Xhosa": "xho",
    "Yao": "yao",
    "Yolngu": "yol",
    "Yoruba": "yor",
    "Zapotec": "zap",
    "Zulu": "zul"
}  

exports.countryAlphaCodeDictionary = {
  "Afghanistan": "flag_AF",
  "Åland Islands": "flag_AX",
  "Albania": "flag_AL",
  "Algeria": "flag_DZ",
  "American Samoa": "flag_AS",
  "Andorra": "flag_AD",
  "Angola": "flag_AO",
  "Anguilla": "flag_AI",
  "Antarctica": "flag_AQ",
  "Antigua and Barbuda": "flag_AG",
  "Argentina": "flag_AR",
  "Armenia": "flag_AM",
  "Aruba": "flag_AW",
  "Australia": "flag_AU",
  "Austria": "flag_AT",
  "Azerbaijan": "flag_AZ",
  "Bahamas": "flag_BS",
  "Bahrain": "flag_BH",
  "Bangladesh": "flag_BD",
  "Barbados": "flag_BB",
  "Belarus": "flag_BY",
  "Belgium": "flag_BE",
  "Belize": "flag_BZ",
  "Benin": "flag_BJ",
  "Bermuda": "flag_BM",
  "Bhutan": "flag_BT",
  "Bolivia": "flag_BO",
  "Bonaire, Sint Eustatius and Saba": "flag_BQ",
  "Bosnia & Herzegovina": "flag_BA",
  "Botswana": "flag_BW",
  "Bouvet Island": "flag_BV",
  "Brazil": "flag_BR",
  "British Indian Ocean Territory": "flag_IO",
  "Brunei Darussalam": "flag_BN",
  "Bulgaria": "flag_BG",
  "Burkina Faso": "flag_BF",
  "Burundi": "flag_BI",
  "Cape Verde": "flag_CV",
  "Cambodia": "flag_KH",
  "Cameroon": "flag_CM",
  "Canada": "flag_CA",
  "Cayman Islands": "flag_KY",
  "Central African Republic": "flag_CF",
  "Chad": "flag_TD",
  "Chile": "flag_CL",
  "China": "flag_CN",
  "Christmas Island": "flag_CX",
  "Cocos (Keeling) Islands": "flag_CC",
  "Colombia": "flag_CO",
  "Comoros": "flag_KM",
  "DR Congo": "flag_CD",
  "Congo": "flag_CG",
  "Cook Islands": "flag_CK",
  "Costa Rica": "flag_CR",
  "Côte d'Ivoire": "flag_CI",
  "Croatia": "flag_HR",
  "Cuba": "flag_CU",
  "Curacao": "flag_CW",
  "Cyprus": "flag_CY",
  "Czechia": "flag_CZ",
  "Denmark": "flag_DK",
  "Djibouti": "flag_DJ",
  "Dominica": "flag_DM",
  "Dominican Republic": "flag_DO",
  "Ecuador": "flag_EC",
  "Egypt": "flag_EG",
  "El Salvador": "flag_SV",
  "Equatorial Guinea": "flag_GQ",
  "Eritrea": "flag_ER",
  "Estonia": "flag_EE",
  "Eswatini": "flag_SZ",
  "Ethiopia": "flag_ET",
  "Falkland Islands": "flag_FK",
  "Faroe Islands": "flag_FO",
  "Fiji": "flag_FJ",
  "Finland": "flag_FI",
  "France": "flag_FR",
  "French Guiana": "flag_GF",
  "French Polynesia": "flag_PF",
  "French Southern Territories": "flag_TF",
  "Gabon": "flag_GA",
  "Gambia": "flag_GM",
  "Georgia": "flag_GE",
  "Germany": "flag_DE",
  "Ghana": "flag_GH",
  "Gibraltar": "flag_GI",
  "Greece": "flag_GR",
  "Greenland": "flag_GL",
  "Grenada": "flag_GD",
  "Guadeloupe": "flag_GP",
  "Guam": "flag_GU",
  "Guatemala": "flag_GT",
  "Guernsey": "flag_GG",
  "Guinea": "flag_GN",
  "Guinea Bissau": "flag_GW",
  "Guyana": "flag_GY",
  "Haiti": "flag_HT",
  "Heard Island and McDonald Islands": "flag_HM",
  "Holy See": "flag_VA",
  "Honduras": "flag_HN",
  "Hong Kong": "flag_HK",
  "Hungary": "flag_HU",
  "Iceland": "flag_IS",
  "India": "flag_IN",
  "Indonesia": "flag_ID",
  "Iran": "flag_IR",
  "Iraq": "flag_IQ",
  "Ireland": "flag_IE",
  "Isle of Man": "flag_IM",
  "Italy": "flag_IT",
  "Jamaica": "flag_JM",
  "Japan": "flag_JP",
  "Jersey": "flag_JE",
  "Jordan": "flag_JO",
  "Kazakhstan": "flag_KZ",
  "Kenya": "flag_KE",
  "Kiribati": "flag_KI",
  "North Korea": "flag_KP",
  "South Korea": "flag_KR",
  "Kuwait": "flag_KW",
  "Kyrgyzstan": "flag_KG",
  "Laos": "flag_LA",
  "Latvia": "flag_LV",
  "Lebanon": "flag_LB",
  "Lesotho": "flag_LS",
  "Liberia": "flag_LR",
  "Libya": "flag_LY",
  "Liechtenstein": "flag_LI",
  "Lithuania": "flag_LT",
  "Luxembourg": "flag_LU",
  "Macao": "flag_MO",
  "North Macedonia": "flag_MK",
  "Madagascar": "flag_MG",
  "Malawi": "flag_MW",
  "Malaysia": "flag_MY",
  "Maldives": "flag_MV",
  "Mali": "flag_ML",
  "Malta": "flag_MT",
  "Marshall Islands": "flag_MH",
  "Martinique": "flag_MQ",
  "Mauritania": "flag_MR",
  "Mauritius": "flag_MU",
  "Mayotte": "flag_YT",
  "Mexico": "flag_MX",
  "Micronesia": "flag_FM",
  "Moldova": "flag_MD",
  "Monaco": "flag_MC",
  "Mongolia": "flag_MN",
  "Montenegro": "flag_ME",
  "Montserrat": "flag_MS",
  "Morocco": "flag_MA",
  "Mozambique": "flag_MZ",
  "Myanmar": "flag_MM",
  "Namibia": "flag_NA",
  "Nauru": "flag_NR",
  "Nepal": "flag_NP",
  "Netherlands": "flag_NL",
  "New Caledonia": "flag_NC",
  "New Zealand": "flag_NZ",
  "Nicaragua": "flag_NI",
  "Niger": "flag_NE",
  "Nigeria": "flag_NG",
  "Niue": "flag_NU",
  "Norfolk Island": "flag_NF",
  "Northern Mariana Islands": "flag_MP",
  "Norway": "flag_NO",
  "Oman": "flag_OM",
  "Pakistan": "flag_PK",
  "Palau": "flag_PW",
  "Palestine": "flag_PS",
  "Panama": "flag_PA",
  "Papua New Guinea": "flag_PG",
  "Paraguay": "flag_PY",
  "Peru": "flag_PE",
  "Philippines": "flag_PH",
  "Pitcairn": "flag_PN",
  "Poland": "flag_PL",
  "Portugal": "flag_PT",
  "Puerto Rico": "flag_PR",
  "Qatar": "flag_QA",
  "Réunion": "flag_RE",
  "Romania": "flag_RO",
  "Russia": "flag_RU",
  "Rwanda": "flag_RW",
  "Saint Barthélemy": "flag_BL",
  "Saint Helena, Ascension and Tristan da Cunha": "flag_SH",
  "Saint Kitts and Nevis": "flag_KN",
  "Saint Lucia": "flag_LC",
  "Saint Martin": "flag_MF",
  "Saint Pierre and Miquelon": "flag_PM",
  "Saint Vincent and the Grenadines": "flag_VC",
  "Samoa": "flag_WS",
  "San Marino": "flag_SM",
  "Sao Tome and Principe": "flag_ST",
  "Saudi Arabia": "flag_SA",
  "Senegal": "flag_SN",
  "Serbia": "flag_RS",
  "Seychelles": "flag_SC",
  "Sierra Leone": "flag_SL",
  "Singapore": "flag_SG",
  "Sint Maarten": "flag_SX",
  "Slovakia": "flag_SK",
  "Slovenia": "flag_SI",
  "Solomon Islands": "flag_SB",
  "Somalia": "flag_SO",
  "South Africa": "flag_ZA",
  "South Georgia and the South Sandwich Islands": "flag_GS",
  "South Sudan": "flag_SS",
  "Spain": "flag_ES",
  "Sri Lanka": "flag_LK",
  "Sudan": "flag_SD",
  "Suriname": "flag_SR",
  "Svalbard and Jan Mayen": "flag_SJ",
  "Sweden": "flag_SE",
  "Switzerland": "flag_CH",
  "Syria": "flag_SY",
  "Taiwan": "flag_TW",
  "Tajikistan": "flag_TJ",
  "Tanzania, the United Republic of": "flag_TZ",
  "Thailand": "flag_TH",
  "Timor-Leste": "flag_TL",
  "Togo": "flag_TG",
  "Tokelau": "flag_TK",
  "Tonga": "flag_TO",
  "Trinidad and Tobago": "flag_TT",
  "Tunisia": "flag_TN",
  "Turkey": "flag_TR",
  "Turkmenistan": "flag_TM",
  "Turks and Caicos Islands": "flag_TC",
  "Tuvalu": "flag_TV",
  "Uganda": "flag_UG",
  "Ukraine": "flag_UA",
  "United Arab Emirates": "flag_AE",
  "United States Minor Outlying Islands": "flag_UM",
  "United States": "flag_US",
  "Uruguay": "flag_UY",
  "Uzbekistan": "flag_UZ",
  "Vanuatu": "flag_VU",
  "Venezuela": "flag_VE",
  "Vietnam": "flag_VN",
  "Virgin Islands (UK)": "flag_VG",
  "Virgin Islands (US)": "flag_VI",
  "Wallis and Futuna": "flag_WF",
  "Western Sahara": "flag_EH",
  "Yemen": "flag_YE",
  "Zambia": "flag_ZM",
  "Zimbabwe": "flag_ZW",
  "England": "england",
  "Scotland": "scotland",
  "Wales": "wales",
  "Northern Ireland": "flag_gb",
  "NotReal" : "flag_il",
  "Kosovo" : "flag_xk"
};
